#!/bin/sh

set -e

OUTPUT="output/mage-$(go env GOOS)-$(go env GOARCH)"

cd ".mage"

FILES="$(go list -tags mage -f '{{ .GoFiles }}' | tr -d '[]')"

for FILE in FILES; do
  if [ ! -e "$OUTPUT" ] || [ "$FILE" -nt "$OUTPUT" ]; then
    mage -compile "$OUTPUT"
    break
  fi
done

cd ..
exec ".mage/$OUTPUT" "$@"

